### ISSUE TITLE
"Unable to send messages to Rollbar API. Produced response:" message before log item

### ISSUE THREAD

**Issue by szekeresa** [rollbar/rollbar-php-laravel#71]
Hi!

I use Laravel 5.1 and rollbar-php-laravel v2.4.1.

"Unable to send messages to Rollbar API. Produced response:" message before log item...
No response text, only this message.

I use other Laravel 5.1 project and rollbar-php-laravel v2.3.0 but no problem, only v2.4.1.

If "**ROLLBAR_LEVEL=error**" defined is .env AND run `Log::error("test")` is OK.
If run `Log::info("test")` then in logfile:
`local.ERROR: Unable to send messages to Rollbar API. Produced response:`
 
If "**ROLLBAR_LEVEL**" not defined in .env then `Log::error("test")` and `Log::info("test")` is OK!

**Comment by jessewgibbs** [comment]
Hey @szekeresa,

We'll take a look into this and get back to you as soon as we can.

**Comment by jessewgibbs** [comment]
@ArturMoczulski can you take a look at this?

**Comment by clin407** [comment]
I'm getting similar issues as well. ROLLBAR_LEVEL=errorr but logging anything under that shows up as that message.

**Comment by ArturMoczulski** [comment]
This has been fixed in `master` and will be included in the upcoming release.

**Comment by mrtimp** [comment]
Thanks @ArturMoczulski :-)

**Comment by szekeresa** [comment]
Thanks @ArturMoczulski 👍

**Comment by clin407** [comment]
I tried doing composer update and it's not still showing the new version? Is it possible to put it into a release?

**Comment by szekeresa** [comment]
@clin407 Change composer.json rollbar-laravel version to dev-laravel-5.5.
`"rollbar/rollbar-laravel": "dev-laravel-5.5",`
